<?php

return [
    'event' => [
        'title' => 'Our Wedding',
        'date' => '2026-07-18',
        'time' => '18:00',
        'timezone' => 'Asia/Jakarta',
        'venue_name' => 'Whistler Garden',
        'venue_address' => 'Jl HR Jl. Rasuna Said, Salembaran, Kosambi, Tangerang Regency, Banten 15214, Indonesia',
        'general_info' => 'Join us for a celebration of love. Dinner and dancing to follow.',
    ],
    'couple' => [
        'groom' => 'Jeffry',
        'bride' => 'Priscilla',
        'groom_name' => 'Jeffry Handani',
        'bride_name' => 'Zefanya Priscilla',
        'groom_photo' => '/images/groom.jpg',
        'bride_photo' => '/images/bride.jpg',
    ],
    'families' => [
        'groom_parents' => ['Mr. Marthios Santioso', 'Mrs. Meitalia Hamidy'],
        'bride_parents' => ['Mr. Welly Sudirman', 'Mrs. Tjong Sioe Fun (Yenny)'],
    ],
    'scripture' => "And now these three remain: faith, hope, and love. But the greatest of these is love.",
    'events' => [
        [
            'title' => 'Holy Matrimony',
            'venue_name' => 'Whistler Garden',
            'venue_room' => 'Sky Glass House',
            'address_line1' => 'Jl HR Jl. Rasuna Said, Salembaran, Kosambi',
            'address_line2' => 'Tangerang Regency, Banten 15214, Indonesia',
            'date' => '2026-07-18',
            'time' => '11:00',
            'timezone' => 'Asia/Jakarta',
            'maps_url' => 'https://maps.app.goo.gl/bg2N2gsNPU32XGUp9',
            'watch_url' => 'https://example.com/live',
        ],
        [
            'title' => 'Wedding Reception',
            'venue_name' => 'Whistler Garden',
            'venue_room' => 'Sky Glass House',
            'address_line1' => 'Jl HR Jl. Rasuna Said, Salembaran, Kosambi',
            'address_line2' => 'Tangerang Regency, Banten 15214, Indonesia',
            'date' => '2026-07-18',
            'time' => '18:30',
            'timezone' => 'Asia/Jakarta',
            'maps_url' => 'https://maps.app.goo.gl/bg2N2gsNPU32XGUp9',
            'watch_url' => null,
        ],
    ],
    'media' => [
        'hero_image_url' => '/images/top.jpg',
        'video_file_url' => null,
        'video_embed_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
        'map_embed_url' => 'https://www.google.com/maps?q=Grand+Ballroom+Jakarta&output=embed',
        'gallery' => [
            ['url' => '/images/gallery-1.jpg', 'alt' => 'Gallery 1'],
            ['url' => '/images/gallery-2.jpg', 'alt' => 'Gallery 2'],
            ['url' => '/images/gallery-3.jpg', 'alt' => 'Gallery 3'],
            ['url' => '/images/gallery-4.jpg', 'alt' => 'Gallery 4'],
            ['url' => '/images/gallery-5.jpg', 'alt' => 'Gallery 5'],
            ['url' => '/images/gallery-6.jpg', 'alt' => 'Gallery 6'],
            // ['url' => '/images/gallery-7.jpg', 'alt' => 'Gallery 7'],
            // ['url' => '/images/gallery-8.jpg', 'alt' => 'Gallery 8'],
        ],
        'book_cover' => '/images/book-cover.jpg'
    ],
    'calendar' => [
        'duration_minutes' => 180,
    ],
    'gifts' => [
        ['label' => 'Gift Registry', 'url' => 'https://example.com/registry'],
        ['label' => 'Online Giving', 'url' => 'https://example.com/giving'],
    ],
    'gifts_modal' => [
        [
            'label' => 'BCA',
            'logo' => '/images/bca.png',
            'account_name' => 'Zefanya Priscilla',
            'account_number' => '6040325822',
            // 'qr_image' => '/images/qr_placeholder.svg',
        ],
        [
            'label' => 'BCA',
            'logo' => '/images/bca.png',
            'account_name' => 'Jeffry Handani',
            'account_number' => '1630664272',
            // 'qr_image' => '/images/qr_placeholder.svg',
        ],
        [
            'label' => 'TNG',
            'logo' => null,
            'account_name' => 'Jeffry Handani',
            'account_number' => null,
            'qr_image' => '/images/tng.jpeg',
        ],
    ],
    'custom_actions' => [
        ['label' => 'Hotel Booking', 'url' => 'https://example.com/hotel'],
        ['label' => 'Dress Code', 'url' => 'https://example.com/dresscode'],
        ['label' => 'Photo Gallery', 'url' => 'https://example.com/gallery'],
        ['label' => 'Contact Us', 'url' => 'mailto:hello@example.com'],
    ],
    'languages' => ['en', 'id'],
    'assets' => [
        'hero_desktop' => '/images/top_desktop.jpg',
        'hero_mobile' => '/images/top.jpg',
        'ornament_divider' => '/images/ornament_divider.svg',
        'icon_matrimony' => '/images/icon_rings.svg',
        'icon_reception' => '/images/icon_glasses.svg',
        'gift_illustration' => '/images/gift_cute.svg',
        'scripture_bg' => '/images/scripture_bg.svg',
    ],
];
