<?php

return [
    'event' => [
        'title' => 'Our Wedding',
        'date' => '2026-07-18',
        'time' => '18:00',
        'timezone' => 'Asia/Jakarta',
        'venue_name' => 'Whistler Garden',
        'venue_address' => 'Jl HR Jl. Rasuna Said, Salembaran, Kosambi, Tangerang Regency, Banten 15214, Indonesia',
        'general_info' => 'Join us for a celebration of love. Dinner and dancing to follow.',
    ],
    'couple' => [
        'groom' => 'Jeffry',
        'bride' => 'Priscilla',
    ],
    'families' => [
        'groom_parents' => ['Mr. Eddy Jericho', 'Mrs. Ana Muliawan'],
        'bride_parents' => ['Mr. Ridwan', 'Mrs. Corry Hanjaya'],
    ],
    'scripture' => "And now these three remain: faith, hope, and love. But the greatest of these is love.",
    'events' => [
        [
            'title' => 'Holy Matrimony',
            'venue_name' => 'Whistler Garden',
            'venue_room' => 'Function Room Scenery',
            'address_line1' => 'Jl HR Jl. Rasuna Said, Salembaran, Kosambi',
            'address_line2' => 'Tangerang Regency, Banten 15214, Indonesia',
            'date' => '2026-07-18',
            'time' => '11:00',
            'timezone' => 'Asia/Jakarta',
            'maps_url' => 'https://maps.app.goo.gl/bg2N2gsNPU32XGUp9',
            'watch_url' => 'https://example.com/live',
        ],
        [
            'title' => 'Wedding Reception',
            'venue_name' => 'Whistler Garden',
            'venue_room' => 'Sky Glass House',
            'address_line1' => 'Jl HR Jl. Rasuna Said, Salembaran, Kosambi',
            'address_line2' => 'Tangerang Regency, Banten 15214, Indonesia',
            'date' => '2026-07-18',
            'time' => '18:30',
            'timezone' => 'Asia/Jakarta',
            'maps_url' => 'https://maps.app.goo.gl/bg2N2gsNPU32XGUp9',
            'watch_url' => null,
        ],
    ],
    'media' => [
        'hero_image_url' => 'https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=1480&auto=format&fit=crop',
        'video_file_url' => null,
        'video_embed_url' => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
        'map_embed_url' => 'https://www.google.com/maps?q=Grand+Ballroom+Jakarta&output=embed',
        'gallery' => [
            ['url' => 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1200&auto=format&fit=crop', 'alt' => 'Engagement'],
            ['url' => 'https://images.unsplash.com/photo-1518600506278-4e8ef466b010?q=80&w=1200&auto=format&fit=crop', 'alt' => 'Bride & Groom'],
            ['url' => 'https://images.unsplash.com/photo-1495567720989-cebdbdd97913?q=80&w=1200&auto=format&fit=crop', 'alt' => 'Ceremony'],
            ['url' => 'https://images.unsplash.com/photo-1519225421980-715cb0216a56?q=80&w=1200&auto=format&fit=crop', 'alt' => 'Reception'],
            ['url' => 'https://placehold.co/1200x800?text=Engagement', 'alt' => 'Engagement'],
            ['url' => 'https://placehold.co/1200x800?text=Bride+%26+Groom', 'alt' => 'Bride & Groom'],
            ['url' => 'https://placehold.co/1200x800?text=Ceremony', 'alt' => 'Ceremony'],
            ['url' => 'https://placehold.co/1200x800?text=Reception', 'alt' => 'Reception'],
        ],
    ],
    'calendar' => [
        'duration_minutes' => 180,
    ],
    'gifts' => [
        ['label' => 'Gift Registry', 'url' => 'https://example.com/registry'],
        ['label' => 'Online Giving', 'url' => 'https://example.com/giving'],
    ],
    'gifts_modal' => [
        [
            'label' => 'BCA',
            'logo' => '/images/bank_bca.svg',
            'account_name' => 'Brian Jericho',
            'account_number' => '6240218591',
            'qr_image' => '/images/qr_placeholder.svg',
        ],
        [
            'label' => 'QRIS',
            'logo' => null,
            'account_name' => null,
            'account_number' => null,
            'qr_image' => '/images/qr_placeholder.svg',
        ],
    ],
    'custom_actions' => [
        ['label' => 'Hotel Booking', 'url' => 'https://example.com/hotel'],
        ['label' => 'Dress Code', 'url' => 'https://example.com/dresscode'],
        ['label' => 'Photo Gallery', 'url' => 'https://example.com/gallery'],
        ['label' => 'Contact Us', 'url' => 'mailto:hello@example.com'],
    ],
    'languages' => ['en', 'id'],
    'assets' => [
        'hero_desktop' => '/images/hero_bg.svg',
        'hero_mobile' => '/images/hero_bg.svg',
        'ornament_divider' => '/images/ornament_divider.svg',
        'icon_matrimony' => '/images/icon_rings.svg',
        'icon_reception' => '/images/icon_glasses.svg',
        'gift_illustration' => '/images/gift_sketch.svg',
    ],
];
